package ClasesMusiteka;

// Generated 17-ago-2013 1:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Clasesproductos generated by hbm2java
 */
public class Clasesproductos implements java.io.Serializable {

	private long idclaseproducto;
	private String descclaseproducto;
	private String link;
	private Set subclasesproductoses = new HashSet(0);
	private Set productoses = new HashSet(0);
	private Set productoses_1 = new HashSet(0);
	private Set subclasesproductoses_1 = new HashSet(0);

	public Clasesproductos() {
	}

	public Clasesproductos(long idclaseproducto, String descclaseproducto,
			String link) {
		this.idclaseproducto = idclaseproducto;
		this.descclaseproducto = descclaseproducto;
		this.link = link;
	}

	public Clasesproductos(long idclaseproducto, String descclaseproducto,
			String link, Set subclasesproductoses, Set productoses,
			Set productoses_1, Set subclasesproductoses_1) {
		this.idclaseproducto = idclaseproducto;
		this.descclaseproducto = descclaseproducto;
		this.link = link;
		this.subclasesproductoses = subclasesproductoses;
		this.productoses = productoses;
		this.productoses_1 = productoses_1;
		this.subclasesproductoses_1 = subclasesproductoses_1;
	}

	public long getIdclaseproducto() {
		return this.idclaseproducto;
	}

	public void setIdclaseproducto(long idclaseproducto) {
		this.idclaseproducto = idclaseproducto;
	}

	public String getDescclaseproducto() {
		return this.descclaseproducto;
	}

	public void setDescclaseproducto(String descclaseproducto) {
		this.descclaseproducto = descclaseproducto;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Set getSubclasesproductoses() {
		return this.subclasesproductoses;
	}

	public void setSubclasesproductoses(Set subclasesproductoses) {
		this.subclasesproductoses = subclasesproductoses;
	}

	public Set getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set productoses) {
		this.productoses = productoses;
	}

	public Set getProductoses_1() {
		return this.productoses_1;
	}

	public void setProductoses_1(Set productoses_1) {
		this.productoses_1 = productoses_1;
	}

	public Set getSubclasesproductoses_1() {
		return this.subclasesproductoses_1;
	}

	public void setSubclasesproductoses_1(Set subclasesproductoses_1) {
		this.subclasesproductoses_1 = subclasesproductoses_1;
	}

}
