package ClasesMusiteka;

// Generated 17-ago-2013 1:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Documentos generated by hbm2java
 */
public class Documentos implements java.io.Serializable {

	private long iddocumento;
	private Tiposdocumentos tiposdocumentos;
	private String documento;
	private Set usuarioses = new HashSet(0);
	private Set usuarioses_1 = new HashSet(0);

	public Documentos() {
	}

	public Documentos(long iddocumento, Tiposdocumentos tiposdocumentos,
			String documento) {
		this.iddocumento = iddocumento;
		this.tiposdocumentos = tiposdocumentos;
		this.documento = documento;
	}

	public Documentos(long iddocumento, Tiposdocumentos tiposdocumentos,
			String documento, Set usuarioses, Set usuarioses_1) {
		this.iddocumento = iddocumento;
		this.tiposdocumentos = tiposdocumentos;
		this.documento = documento;
		this.usuarioses = usuarioses;
		this.usuarioses_1 = usuarioses_1;
	}

	public long getIddocumento() {
		return this.iddocumento;
	}

	public void setIddocumento(long iddocumento) {
		this.iddocumento = iddocumento;
	}

	public Tiposdocumentos getTiposdocumentos() {
		return this.tiposdocumentos;
	}

	public void setTiposdocumentos(Tiposdocumentos tiposdocumentos) {
		this.tiposdocumentos = tiposdocumentos;
	}

	public String getDocumento() {
		return this.documento;
	}

	public void setDocumento(String documento) {
		this.documento = documento;
	}

	public Set getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set usuarioses) {
		this.usuarioses = usuarioses;
	}

	public Set getUsuarioses_1() {
		return this.usuarioses_1;
	}

	public void setUsuarioses_1(Set usuarioses_1) {
		this.usuarioses_1 = usuarioses_1;
	}

}
