package ClasesMusiteka;

// Generated 17-ago-2013 1:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Domicilios generated by hbm2java
 */
public class Domicilios implements java.io.Serializable {

	private long iddomicilio;
	private Paises paises;
	private String nombrevia;
	private String numeropiso;
	private long codigopostal;
	private String localidadprovincia;
	private Set usuarioses = new HashSet(0);
	private Set usuarioses_1 = new HashSet(0);

	public Domicilios() {
	}

	public Domicilios(long iddomicilio, Paises paises, String nombrevia,
			long codigopostal, String localidadprovincia) {
		this.iddomicilio = iddomicilio;
		this.paises = paises;
		this.nombrevia = nombrevia;
		this.codigopostal = codigopostal;
		this.localidadprovincia = localidadprovincia;
	}

	public Domicilios(long iddomicilio, Paises paises, String nombrevia,
			String numeropiso, long codigopostal, String localidadprovincia,
			Set usuarioses, Set usuarioses_1) {
		this.iddomicilio = iddomicilio;
		this.paises = paises;
		this.nombrevia = nombrevia;
		this.numeropiso = numeropiso;
		this.codigopostal = codigopostal;
		this.localidadprovincia = localidadprovincia;
		this.usuarioses = usuarioses;
		this.usuarioses_1 = usuarioses_1;
	}

	public long getIddomicilio() {
		return this.iddomicilio;
	}

	public void setIddomicilio(long iddomicilio) {
		this.iddomicilio = iddomicilio;
	}

	public Paises getPaises() {
		return this.paises;
	}

	public void setPaises(Paises paises) {
		this.paises = paises;
	}

	public String getNombrevia() {
		return this.nombrevia;
	}

	public void setNombrevia(String nombrevia) {
		this.nombrevia = nombrevia;
	}

	public String getNumeropiso() {
		return this.numeropiso;
	}

	public void setNumeropiso(String numeropiso) {
		this.numeropiso = numeropiso;
	}

	public long getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(long codigopostal) {
		this.codigopostal = codigopostal;
	}

	public String getLocalidadprovincia() {
		return this.localidadprovincia;
	}

	public void setLocalidadprovincia(String localidadprovincia) {
		this.localidadprovincia = localidadprovincia;
	}

	public Set getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set usuarioses) {
		this.usuarioses = usuarioses;
	}

	public Set getUsuarioses_1() {
		return this.usuarioses_1;
	}

	public void setUsuarioses_1(Set usuarioses_1) {
		this.usuarioses_1 = usuarioses_1;
	}

}
