package ClasesMusiteka;

// Generated 17-ago-2013 1:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Paises generated by hbm2java
 */
public class Paises implements java.io.Serializable {

	private long idpais;
	private String nombrepais;
	private Set domicilioses = new HashSet(0);
	private Set domicilioses_1 = new HashSet(0);

	public Paises() {
	}

	public Paises(long idpais, String nombrepais) {
		this.idpais = idpais;
		this.nombrepais = nombrepais;
	}

	public Paises(long idpais, String nombrepais, Set domicilioses,
			Set domicilioses_1) {
		this.idpais = idpais;
		this.nombrepais = nombrepais;
		this.domicilioses = domicilioses;
		this.domicilioses_1 = domicilioses_1;
	}

	public long getIdpais() {
		return this.idpais;
	}

	public void setIdpais(long idpais) {
		this.idpais = idpais;
	}

	public String getNombrepais() {
		return this.nombrepais;
	}

	public void setNombrepais(String nombrepais) {
		this.nombrepais = nombrepais;
	}

	public Set getDomicilioses() {
		return this.domicilioses;
	}

	public void setDomicilioses(Set domicilioses) {
		this.domicilioses = domicilioses;
	}

	public Set getDomicilioses_1() {
		return this.domicilioses_1;
	}

	public void setDomicilioses_1(Set domicilioses_1) {
		this.domicilioses_1 = domicilioses_1;
	}

}
