package ClasesMusiteka;

// Generated 17-ago-2013 1:35:04 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private long idproducto;
	private Clasesproductos clasesproductos;
	private Subclasesproductos subclasesproductos;
	private String marca;
	private String modelo;
	private BigDecimal precio;
	private String enventa;
	private String observaciones;

	public Productos() {
	}

	public Productos(long idproducto, Clasesproductos clasesproductos,
			Subclasesproductos subclasesproductos, String marca, String modelo,
			BigDecimal precio, String enventa) {
		this.idproducto = idproducto;
		this.clasesproductos = clasesproductos;
		this.subclasesproductos = subclasesproductos;
		this.marca = marca;
		this.modelo = modelo;
		this.precio = precio;
		this.enventa = enventa;
	}

	public Productos(long idproducto, Clasesproductos clasesproductos,
			Subclasesproductos subclasesproductos, String marca, String modelo,
			BigDecimal precio, String enventa, String observaciones) {
		this.idproducto = idproducto;
		this.clasesproductos = clasesproductos;
		this.subclasesproductos = subclasesproductos;
		this.marca = marca;
		this.modelo = modelo;
		this.precio = precio;
		this.enventa = enventa;
		this.observaciones = observaciones;
	}

	public long getIdproducto() {
		return this.idproducto;
	}

	public void setIdproducto(long idproducto) {
		this.idproducto = idproducto;
	}

	public Clasesproductos getClasesproductos() {
		return this.clasesproductos;
	}

	public void setClasesproductos(Clasesproductos clasesproductos) {
		this.clasesproductos = clasesproductos;
	}

	public Subclasesproductos getSubclasesproductos() {
		return this.subclasesproductos;
	}

	public void setSubclasesproductos(Subclasesproductos subclasesproductos) {
		this.subclasesproductos = subclasesproductos;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public String getEnventa() {
		return this.enventa;
	}

	public void setEnventa(String enventa) {
		this.enventa = enventa;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
