package ClasesMusiteka;

// Generated 17-ago-2013 1:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tiposdocumentos generated by hbm2java
 */
public class Tiposdocumentos implements java.io.Serializable {

	private long idtipodocumento;
	private String desctipodocumento;
	private Set documentoses = new HashSet(0);
	private Set documentoses_1 = new HashSet(0);

	public Tiposdocumentos() {
	}

	public Tiposdocumentos(long idtipodocumento, String desctipodocumento) {
		this.idtipodocumento = idtipodocumento;
		this.desctipodocumento = desctipodocumento;
	}

	public Tiposdocumentos(long idtipodocumento, String desctipodocumento,
			Set documentoses, Set documentoses_1) {
		this.idtipodocumento = idtipodocumento;
		this.desctipodocumento = desctipodocumento;
		this.documentoses = documentoses;
		this.documentoses_1 = documentoses_1;
	}

	public long getIdtipodocumento() {
		return this.idtipodocumento;
	}

	public void setIdtipodocumento(long idtipodocumento) {
		this.idtipodocumento = idtipodocumento;
	}

	public String getDesctipodocumento() {
		return this.desctipodocumento;
	}

	public void setDesctipodocumento(String desctipodocumento) {
		this.desctipodocumento = desctipodocumento;
	}

	public Set getDocumentoses() {
		return this.documentoses;
	}

	public void setDocumentoses(Set documentoses) {
		this.documentoses = documentoses;
	}

	public Set getDocumentoses_1() {
		return this.documentoses_1;
	}

	public void setDocumentoses_1(Set documentoses_1) {
		this.documentoses_1 = documentoses_1;
	}

}
