package ClasesMusiteka;

// Generated 17-ago-2013 1:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tiposusuarios generated by hbm2java
 */
public class Tiposusuarios implements java.io.Serializable {

	private long idtipousuario;
	private String desctipousuario;
	private Set usuarioses = new HashSet(0);
	private Set usuarioses_1 = new HashSet(0);

	public Tiposusuarios() {
	}

	public Tiposusuarios(long idtipousuario) {
		this.idtipousuario = idtipousuario;
	}

	public Tiposusuarios(long idtipousuario, String desctipousuario,
			Set usuarioses, Set usuarioses_1) {
		this.idtipousuario = idtipousuario;
		this.desctipousuario = desctipousuario;
		this.usuarioses = usuarioses;
		this.usuarioses_1 = usuarioses_1;
	}

	public long getIdtipousuario() {
		return this.idtipousuario;
	}

	public void setIdtipousuario(long idtipousuario) {
		this.idtipousuario = idtipousuario;
	}

	public String getDesctipousuario() {
		return this.desctipousuario;
	}

	public void setDesctipousuario(String desctipousuario) {
		this.desctipousuario = desctipousuario;
	}

	public Set getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set usuarioses) {
		this.usuarioses = usuarioses;
	}

	public Set getUsuarioses_1() {
		return this.usuarioses_1;
	}

	public void setUsuarioses_1(Set usuarioses_1) {
		this.usuarioses_1 = usuarioses_1;
	}

}
