package ClasesMusiteka;

// Generated 17-ago-2013 1:35:04 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private long idusuario;
	private Tiposusuarios tiposusuarios;
	private Documentos documentos;
	private Domicilios domicilios;
	private String nombre;
	private String apellidos;
	private String email;
	private String password;
	private String tratamiento;
	private Set transaccioneses = new HashSet(0);
	private Set transaccioneses_1 = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(long idusuario, Tiposusuarios tiposusuarios,
			Documentos documentos, Domicilios domicilios, String nombre,
			String apellidos, String email, String password, String tratamiento) {
		this.idusuario = idusuario;
		this.tiposusuarios = tiposusuarios;
		this.documentos = documentos;
		this.domicilios = domicilios;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
		this.password = password;
		this.tratamiento = tratamiento;
	}

	public Usuarios(long idusuario, Tiposusuarios tiposusuarios,
			Documentos documentos, Domicilios domicilios, String nombre,
			String apellidos, String email, String password,
			String tratamiento, Set transaccioneses, Set transaccioneses_1) {
		this.idusuario = idusuario;
		this.tiposusuarios = tiposusuarios;
		this.documentos = documentos;
		this.domicilios = domicilios;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
		this.password = password;
		this.tratamiento = tratamiento;
		this.transaccioneses = transaccioneses;
		this.transaccioneses_1 = transaccioneses_1;
	}

	public long getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(long idusuario) {
		this.idusuario = idusuario;
	}

	public Tiposusuarios getTiposusuarios() {
		return this.tiposusuarios;
	}

	public void setTiposusuarios(Tiposusuarios tiposusuarios) {
		this.tiposusuarios = tiposusuarios;
	}

	public Documentos getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Documentos documentos) {
		this.documentos = documentos;
	}

	public Domicilios getDomicilios() {
		return this.domicilios;
	}

	public void setDomicilios(Domicilios domicilios) {
		this.domicilios = domicilios;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getTratamiento() {
		return this.tratamiento;
	}

	public void setTratamiento(String tratamiento) {
		this.tratamiento = tratamiento;
	}

	public Set getTransaccioneses() {
		return this.transaccioneses;
	}

	public void setTransaccioneses(Set transaccioneses) {
		this.transaccioneses = transaccioneses;
	}

	public Set getTransaccioneses_1() {
		return this.transaccioneses_1;
	}

	public void setTransaccioneses_1(Set transaccioneses_1) {
		this.transaccioneses_1 = transaccioneses_1;
	}

}
